services:
  - type: web
    name: keiba-csv-web
    env: python
    plan: free
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATA_DIR
        value: /data
    disk:
      name: csvdata
      mountPath: /data
      sizeGB: 1

  - type: worker
    name: keiba-scraper-worker
    env: python
    plan: free
    runtime: python
    buildCommand: ""
    startCommand: python scrape_rakuten_keiba_2024.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATA_DIR
        value: /data
      - key: USER_AGENT
        value: "Mozilla/5.0 (compatible; KeibaStudyBot/1.0; +https://example.com/)"
      - key: SLEEP_SECONDS
        value: "1.5"
    disk:
      name: csvdata
      mountPath: /data
      sizeGB: 1

cronJobs:
  - name: scrape-daily-0030
    schedule: "30 0 * * *"   # JSTで毎日00:30に開始（RenderのTZはUTCなので調整が必要なら後述）
    task:
      type: worker
      name: keiba-scraper-worker
      env: python
      startCommand: python scrape_rakuten_keiba_2024.py