services:
  - type: web
    name: keiba-csv-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATA_DIR
        value: /data

  - type: worker
    name: keiba-scraper-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python scrape_rakuten_keiba_2024.py
    envVars:
      - key: DATA_DIR
        value: /data
      - key: USER_AGENT
        value: Mozilla/5.0 (compatible; KeibaStudyBot/1.0)
      - key: SLEEP_SECONDS
        value: "1.5"
      - key: YEAR
        value: "2024"